In [1]:
import pandas as pd
from plotting import CandlePlot
pd.set_option('display.max_columns', None)

In [2]:
df_ma_res = pd.read_pickle('../data/ma_res.pkl')
df_ma_trades = pd.read_pickle('../data/ma_trades.pkl')

In [3]:
df_ma_res.granularity.unique()

array(['H1', 'H4'], dtype=object)

In [4]:
df_ma_res_h1 = df_ma_res[df_ma_res.granularity == 'H1'].copy()
df_ma_trades_h1 = df_ma_trades[df_ma_trades.granularity == 'H1'].copy()

In [5]:
df_ma_trades_h1.shape

(16476, 32)

In [6]:
df_ma_trades_h1.columns

Index(['time', 'volume', 'mid_o', 'mid_h', 'mid_l', 'mid_c', 'bid_o', 'bid_h',
       'bid_l', 'bid_c', 'ask_o', 'ask_h', 'ask_l', 'ask_c', 'MA_40', 'MA_10',
       'MA_80', 'MA_20', 'MA_150', 'MA_120', 'MA_30', 'DELTA', 'DELTA_PREV',
       'TRADE', 'DIFF', 'GAIN', 'granularity', 'pair', 'GAIN_C', 'ma_l',
       'ma_s', 'cross'],
      dtype='object')

In [7]:
df_cross_summary = df_ma_res_h1[['pair_name', 'num_trades', 'total_gain' , 'cross']].copy()

In [8]:
df_cross_summary

    pair_name  num_trades  total_gain         cross
0     EUR_USD         215        -161   MA_20_MA_10
1     EUR_USD         108         265   MA_40_MA_10
2     EUR_USD         108        -623   MA_40_MA_20
3     EUR_USD         122         -69   MA_40_MA_30
4     EUR_USD          78        -363   MA_80_MA_10
..        ...         ...         ...           ...
235   CAD_JPY          37        -152  MA_120_MA_40
236   CAD_JPY          51        -159  MA_150_MA_10
237   CAD_JPY          35        -151  MA_150_MA_20
238   CAD_JPY          33        -167  MA_150_MA_30
239   CAD_JPY          25          88  MA_150_MA_40

[240 rows x 4 columns]

In [9]:
df_cross_gr = df_cross_summary.groupby("cross", as_index=False).sum(numeric_only=True)
df_cross_gr.sort_values('total_gain', ascending=False, inplace=True)
df_cross_gr.head(10)

           cross  num_trades  total_gain
7   MA_150_MA_40         416        9907
6   MA_150_MA_30         470        8758
2   MA_120_MA_30         559        7468
3   MA_120_MA_40         496        6797
4   MA_150_MA_10         742        6428
5   MA_150_MA_20         570        6223
0   MA_120_MA_10         838        4615
14   MA_80_MA_30         772        3713
12   MA_80_MA_10        1079        3665
15   MA_80_MA_40         746        3613

In [10]:
total_pairs = len(df_ma_res_h1.pair_name.unique())
total_pairs

15

In [11]:
temp = df_ma_res_h1[df_ma_res_h1.cross == "MA_10_MA_40"]

In [12]:
temp[temp.total_gain > 0].shape[0]

0

In [13]:
for c in df_ma_res_h1.cross.unique():
    temp = df_ma_res_h1[df_ma_res_h1.cross == c]
    pg = temp[temp.total_gain > 0].shape[0]
    print(f"{c}: {pg} positive trades out of {temp.shape[0]} ({pg/temp.shape[0]*100:.2f}%)")

MA_20_MA_10: 8 positive trades out of 15 (53.33%)
MA_40_MA_10: 8 positive trades out of 15 (53.33%)
MA_40_MA_20: 6 positive trades out of 15 (40.00%)
MA_40_MA_30: 9 positive trades out of 15 (60.00%)
MA_80_MA_10: 9 positive trades out of 15 (60.00%)
MA_80_MA_20: 7 positive trades out of 15 (46.67%)
MA_80_MA_30: 9 positive trades out of 15 (60.00%)
MA_80_MA_40: 8 positive trades out of 15 (53.33%)
MA_120_MA_10: 11 positive trades out of 15 (73.33%)
MA_120_MA_20: 7 positive trades out of 15 (46.67%)
MA_120_MA_30: 9 positive trades out of 15 (60.00%)
MA_120_MA_40: 7 positive trades out of 15 (46.67%)
MA_150_MA_10: 10 positive trades out of 15 (66.67%)
MA_150_MA_20: 8 positive trades out of 15 (53.33%)
MA_150_MA_30: 10 positive trades out of 15 (66.67%)
MA_150_MA_40: 10 positive trades out of 15 (66.67%)

In [25]:
cross = "MA_40_MA_10"
df_MA_40_MA_10 = df_ma_res_h1[df_ma_res_h1.cross == cross].copy()
df_MA_40_MA_10.sort_values(by= 'total_gain', ascending=False, inplace=True)
df_MA_40_MA_10.head(15)

,pair_name,num_trades,total_gain,mean_gain,min_gain,max_gain,ma_l,ma_s,cross,granularity
65,EUR_CAD,98,1507,15,-82,238,MA_40,MA_10,MA_40_MA_10,H1
161,GBP_CAD,94,1355,14,-90,359,MA_40,MA_10,MA_40_MA_10,H1
49,EUR_AUD,104,945,9,-111,292,MA_40,MA_10,MA_40_MA_10,H1
113,GBP_USD,112,457,4,-119,332,MA_40,MA_10,MA_40_MA_10,H1
129,GBP_JPY,109,283,2,-316,1082,MA_40,MA_10,MA_40_MA_10,H1
1,EUR_USD,108,265,2,-148,186,MA_40,MA_10,MA_40_MA_10,H1
33,EUR_JPY,111,63,0,-191,656,MA_40,MA_10,MA_40_MA_10,H1
193,AUD_JPY,115,4,0,-121,554,MA_40,MA_10,MA_40_MA_10,H1
81,USD_JPY,119,-61,0,-232,775,MA_40,MA_10,MA_40_MA_10,H1
225,CAD_JPY,129,-85,0,-136,544,MA_40,MA_10,MA_40_MA_10,H1
17,EUR_GBP,129,-339,-2,-54,139,MA_40,MA_10,MA_40_MA_10,H1
209,AUD_CAD,127,-373,-2,-67,143,MA_40,MA_10,MA_40_MA_10,H1
177,AUD_USD,121,-401,-3,-79,191,MA_40,MA_10,MA_40_MA_10,H1
97,USD_CAD,118,-440,-3,-134,267,MA_40,MA_10,MA_40_MA_10,H1
145,GBP_AUD,117,-652,-5,-170,321,MA_40,MA_10,MA_40_MA_10,H1

In [15]:
df_gains = df_ma_trades_h1[(df_ma_trades_h1.cross==cross)&
                           (df_ma_trades_h1.pair=="EUR_AUD")].copy()

In [16]:
df_gains

Empty DataFrame
Columns: [time, volume, mid_o, mid_h, mid_l, mid_c, bid_o, bid_h, bid_l, bid_c, ask_o, ask_h, ask_l, ask_c, MA_40, MA_10, MA_80, MA_20, MA_150, MA_120, MA_30, DELTA, DELTA_PREV, TRADE, DIFF, GAIN, granularity, pair, GAIN_C, ma_l, ma_s, cross]
Index: []

In [17]:
cp = CandlePlot(df_gains, candles=False)
cp.show_plot(line_traces=['GAIN_C'])

In [23]:
for curr in df_MA_40_MA_10[df_MA_40_MA_10.total_gain > 0].pair_name.unique():
    temp_gains = df_ma_trades_h1[(df_ma_trades_h1.cross==cross)&
                           (df_ma_trades_h1.pair==curr)].copy()
    print(curr, int(temp_gains.GAIN.sum()))
    cp = CandlePlot(temp_gains, candles=False)
    cp.show_plot(line_traces=['GAIN_C'])

EUR_CAD 0

GBP_CAD 0

EUR_AUD 0

GBP_USD 0

GBP_JPY 0

EUR_USD 0

EUR_JPY 0

AUD_JPY 0

In [27]:
import pandas as pd
from plotting import CandlePlot
pd.set_option("display.max_columns", None)

In [28]:
df_ma_res = pd.read_pickle("../data/ma_res.pkl")
df_ma_trades = pd.read_pickle("../data/ma_trades.pkl")

In [29]:
df_ma_res.granularity.unique()

array(['H1', 'H4'], dtype=object)

In [30]:
df_ma_res_h1 = df_ma_res[df_ma_res.granularity == "H1"].copy()
df_ma_trades_h1 = df_ma_trades[df_ma_trades.granularity == "H1"].copy()

In [31]:
df_ma_trades_h1.shape

(16476, 32)

In [32]:
df_ma_res_h1.columns

Index(['pair_name', 'num_trades', 'total_gain', 'mean_gain', 'min_gain',
       'max_gain', 'ma_l', 'ma_s', 'cross', 'granularity'],
      dtype='object')

In [34]:
df_cross_summary = df_ma_res_h1[['pair_name', 'num_trades', 'total_gain','cross']].copy()

In [35]:
df_cross_gr = df_cross_summary.groupby(by="cross", as_index=False).sum()
df_cross_gr.sort_values(by="total_gain", ascending=False, inplace=True)

In [36]:
df_cross_gr.head()

,cross,pair_name,num_trades,total_gain
7,MA_150_MA_40,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,416,9907
6,MA_150_MA_30,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,470,8758
2,MA_120_MA_30,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,559,7468
3,MA_120_MA_40,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,496,6797
4,MA_150_MA_10,EUR_USDEUR_GBPEUR_JPYEUR_AUDEUR_CADUSD_JPYUSD_...,742,6428

In [38]:
total_pairs = len(df_ma_res_h1.pair_name.unique())

In [39]:
total_pairs

15

In [40]:
temp = df_ma_res_h1[df_ma_res_h1.cross == "MA_10_MA_40"]

In [41]:
temp[temp.total_gain > 0].shape[0]

0

In [42]:
for c in df_ma_res_h1.cross.unique():
    temp = df_ma_res_h1[df_ma_res_h1.cross == c]
    pg = temp[temp.total_gain > 0].shape[0]
    print(f"{c} pg:{pg} perc gain:{(pg / total_pairs) * 100:.0f}%")

MA_20_MA_10 pg:8 perc gain:53%
MA_40_MA_10 pg:8 perc gain:53%
MA_40_MA_20 pg:6 perc gain:40%
MA_40_MA_30 pg:9 perc gain:60%
MA_80_MA_10 pg:9 perc gain:60%
MA_80_MA_20 pg:7 perc gain:47%
MA_80_MA_30 pg:9 perc gain:60%
MA_80_MA_40 pg:8 perc gain:53%
MA_120_MA_10 pg:11 perc gain:73%
MA_120_MA_20 pg:7 perc gain:47%
MA_120_MA_30 pg:9 perc gain:60%
MA_120_MA_40 pg:7 perc gain:47%
MA_150_MA_10 pg:10 perc gain:67%
MA_150_MA_20 pg:8 perc gain:53%
MA_150_MA_30 pg:10 perc gain:67%
MA_150_MA_40 pg:10 perc gain:67%

In [43]:
cross = "MA_40_MA_20"
df_MA_40_MA_20 = df_ma_res_h1[df_ma_res_h1.cross == cross].copy()
df_MA_40_MA_20.sort_values(by="total_gain", ascending=False, inplace=True)

In [44]:
df_MA_40_MA_20

,pair_name,num_trades,total_gain,mean_gain,min_gain,max_gain,ma_l,ma_s,cross,granularity
130,GBP_JPY,99,1278,12,-298,1199,MA_40,MA_20,MA_40_MA_20,H1
50,EUR_AUD,91,1111,12,-133,302,MA_40,MA_20,MA_40_MA_20,H1
66,EUR_CAD,90,991,11,-89,178,MA_40,MA_20,MA_40_MA_20,H1
162,GBP_CAD,94,618,6,-115,400,MA_40,MA_20,MA_40_MA_20,H1
226,CAD_JPY,106,361,3,-162,497,MA_40,MA_20,MA_40_MA_20,H1
114,GBP_USD,102,4,0,-124,327,MA_40,MA_20,MA_40_MA_20,H1
194,AUD_JPY,117,-325,-2,-170,542,MA_40,MA_20,MA_40_MA_20,H1
18,EUR_GBP,105,-330,-3,-62,174,MA_40,MA_20,MA_40_MA_20,H1
178,AUD_USD,108,-427,-3,-98,180,MA_40,MA_20,MA_40_MA_20,H1
2,EUR_USD,108,-623,-5,-171,154,MA_40,MA_20,MA_40_MA_20,H1
98,USD_CAD,105,-684,-6,-151,257,MA_40,MA_20,MA_40_MA_20,H1
146,GBP_AUD,111,-883,-7,-219,311,MA_40,MA_20,MA_40_MA_20,H1
210,AUD_CAD,119,-930,-7,-159,149,MA_40,MA_20,MA_40_MA_20,H1
82,USD_JPY,106,-1098,-10,-238,745,MA_40,MA_20,MA_40_MA_20,H1
34,EUR_JPY,101,-1334,-13,-245,635,MA_40,MA_20,MA_40_MA_20,H1

In [45]:
df_gains = df_ma_trades_h1[(df_ma_trades_h1.cross==cross)&
                           (df_ma_trades_h1.pair=="CAD_JPY")].copy()

In [46]:
df_gains.head(3)

Empty DataFrame
Columns: [time, volume, mid_o, mid_h, mid_l, mid_c, bid_o, bid_h, bid_l, bid_c, ask_o, ask_h, ask_l, ask_c, MA_40, MA_10, MA_80, MA_20, MA_150, MA_120, MA_30, DELTA, DELTA_PREV, TRADE, DIFF, GAIN, granularity, pair, GAIN_C, ma_l, ma_s, cross]
Index: []

In [ ]:
cp = CandlePlot(df_gains, candles=False)
cp.show_plot(line_traces=['GAIN_C'])

In [47]:
for curr in df_MA_40_MA_20[df_MA_40_MA_20.total_gain > 0].pair_name.unique():
    temp_gains = df_ma_trades_h1[(df_ma_trades_h1.cross==cross)&
                           (df_ma_trades_h1.pair==curr)].copy()
    print(curr, int(temp_gains.GAIN.sum()))
    cp = CandlePlot(temp_gains, candles=False)
    cp.show_plot(line_traces=['GAIN_C'])

GBP_JPY 0

EUR_AUD 0

EUR_CAD 0

GBP_CAD 0

CAD_JPY 0

GBP_USD 0