In [2]:
import pandas as pd
from plotting import CandlePlot
pd.set_option('display.max_columns', None)

In [3]:
df_ma_res = pd.read_pickle('../data/ma_res.pkl')
df_ma_trades = pd.read_pickle('../data/ma_trades.pkl')

In [4]:
df_ma_res.granularity.unique()

array(['H1', 'H4'], dtype=object)

In [6]:
df_ma_res_h1 = df_ma_res[df_ma_res.granularity == 'H1'].copy()
df_ma_trades_h1 = df_ma_trades[df_ma_trades.granularity == 'H1'].copy()

In [9]:
df_ma_trades_h1.shape

(16476, 32)

In [11]:
df_ma_res_h1.columns

Index(['pair_name', 'num_trades', 'total_gain', 'mean_gain', 'min_gain',
       'max_gain', 'ma_l', 'ma_s', 'cross', 'granularity'],
      dtype='object')

In [13]:
df_cross_summary = df_ma_res_h1[['pair_name', 'num_trades', 'total_gain' , 'cross']].copy()

In [14]:
df_cross_summary

    pair_name  num_trades  total_gain         cross
0     EUR_USD         215        -161   MA_20_MA_10
1     EUR_USD         108         265   MA_40_MA_10
2     EUR_USD         108        -623   MA_40_MA_20
3     EUR_USD         122         -69   MA_40_MA_30
4     EUR_USD          78        -363   MA_80_MA_10
..        ...         ...         ...           ...
235   CAD_JPY          37        -152  MA_120_MA_40
236   CAD_JPY          51        -159  MA_150_MA_10
237   CAD_JPY          35        -151  MA_150_MA_20
238   CAD_JPY          33        -167  MA_150_MA_30
239   CAD_JPY          25          88  MA_150_MA_40

[240 rows x 4 columns]

In [19]:
df_cross_gr = df_cross_summary.groupby("cross", as_index=False).sum(numeric_only=True)
df_cross_gr.sort_values('total_gain', ascending=False, inplace=True)
df_cross_gr

           cross  num_trades  total_gain
7   MA_150_MA_40         416        9907
6   MA_150_MA_30         470        8758
2   MA_120_MA_30         559        7468
3   MA_120_MA_40         496        6797
4   MA_150_MA_10         742        6428
5   MA_150_MA_20         570        6223
0   MA_120_MA_10         838        4615
14   MA_80_MA_30         772        3713
12   MA_80_MA_10        1079        3665
15   MA_80_MA_40         746        3613
1   MA_120_MA_20         656        3530
9    MA_40_MA_10        1711        2528
11   MA_40_MA_30        1796        2241
13   MA_80_MA_20         859        2017
8    MA_20_MA_10        3204         990
10   MA_40_MA_20        1562       -2271