In [58]:
import sys
sys.path.append('../')
import pandas as pd
import datetime as dt
from plotting import CandlePlot
import plotly.graph_objects as go
from infrastructure.instrument_collection import instrumentCollection as ic

In [59]:
pair = 'GBP_JPY'
granularity = 'H4'
df = pd.read_pickle(f'../data/{pair}_{granularity}.pkl')
MA_LIST = [10, 20, 50, 100, 200]

In [60]:

df_ma = df[['time','mid_o','mid_h','mid_l','mid_c']].copy()

In [61]:
df_ma.tail()

                          time    mid_o    mid_h    mid_l    mid_c
3995 2025-01-26 22:00:00+00:00  194.226  194.361  193.474  193.563
3996 2025-01-27 02:00:00+00:00  193.569  194.316  193.471  194.252
3997 2025-01-27 06:00:00+00:00  194.252  194.654  192.606  193.044
3998 2025-01-27 10:00:00+00:00  193.044  193.152  192.158  192.805
3999 2025-01-27 14:00:00+00:00  192.806  193.078  192.174  192.482

In [62]:
# Note that the first 9 rows will have NaN values in the MA_10 column
# Similarly, the first 19 rows will have NaN values in the MA_20 column.
# We need to pay attention to this while doing analysis, and backtesting.

for ma in MA_LIST:
    df_ma[f'MA_{ma}'] = df_ma['mid_c'].rolling(window=ma).mean()


df_ma.dropna(inplace = True)
df_ma.reset_index(drop=True, inplace=True)
df_ma.head()

,time,mid_o,mid_h,mid_l,mid_c,MA_10,MA_20,MA_50,MA_100,MA_200
0,2022-08-17 05:00:00+00:00,162.583,163.392,162.482,163.174,161.8321,161.71250,162.32144,162.62093,163.256840
1,2022-08-17 09:00:00+00:00,163.174,163.368,162.896,162.974,162.0605,161.74000,162.34340,162.60435,163.253090
2,2022-08-17 13:00:00+00:00,162.976,163.570,162.792,163.032,162.3270,161.77840,162.37156,162.58949,163.248335
3,2022-08-17 17:00:00+00:00,163.030,163.224,162.622,162.752,162.5194,161.82035,162.38692,162.56981,163.249945
4,2022-08-17 21:00:00+00:00,162.701,162.877,162.430,162.468,162.6436,161.84195,162.37192,162.55127,163.247515

In [63]:
df_plot = df_ma.iloc[:500]
df_plot.shape
print(df_plot.columns)

cp = CandlePlot(df_plot)
traces = [f"MA_{x}" for x in MA_LIST]
cp.show_plot(line_traces=traces)

Index(['time', 'mid_o', 'mid_h', 'mid_l', 'mid_c', 'MA_10', 'MA_20', 'MA_50',
       'MA_100', 'MA_200'],
      dtype='object')

In [64]:
MA_S = "MA_50"
MA_L = "MA_200"
BUY = 1
SELL = -1
NONE = 0

In [65]:
df_an = df_ma[['time','mid_o','mid_h','mid_l','mid_c',MA_S,MA_L]].copy()
df_an.head()

,time,mid_o,mid_h,mid_l,mid_c,MA_50,MA_200
0,2022-08-17 05:00:00+00:00,162.583,163.392,162.482,163.174,162.32144,163.256840
1,2022-08-17 09:00:00+00:00,163.174,163.368,162.896,162.974,162.34340,163.253090
2,2022-08-17 13:00:00+00:00,162.976,163.570,162.792,163.032,162.37156,163.248335
3,2022-08-17 17:00:00+00:00,163.030,163.224,162.622,162.752,162.38692,163.249945
4,2022-08-17 21:00:00+00:00,162.701,162.877,162.430,162.468,162.37192,163.247515

In [66]:
df_an['DELTA'] = df_an.MA_50 - df_an.MA_200
df_an.head(50)

,time,mid_o,mid_h,mid_l,mid_c,MA_50,MA_200,DELTA
0,2022-08-17 05:00:00+00:00,162.583,163.392,162.482,163.174,162.32144,163.256840,-0.935400
1,2022-08-17 09:00:00+00:00,163.174,163.368,162.896,162.974,162.34340,163.253090,-0.909690
2,2022-08-17 13:00:00+00:00,162.976,163.570,162.792,163.032,162.37156,163.248335,-0.876775
3,2022-08-17 17:00:00+00:00,163.030,163.224,162.622,162.752,162.38692,163.249945,-0.863025
4,2022-08-17 21:00:00+00:00,162.701,162.877,162.430,162.468,162.37192,163.247515,-0.875595
5,2022-08-18 01:00:00+00:00,162.468,162.690,162.370,162.630,162.36518,163.243080,-0.877900
6,2022-08-18 05:00:00+00:00,162.628,163.083,162.284,162.894,162.35942,163.240840,-0.881420
7,2022-08-18 09:00:00+00:00,162.896,163.246,162.430,162.584,162.34426,163.236750,-0.892490
8,2022-08-18 13:00:00+00:00,162.589,162.637,161.684,161.915,162.31638,163.226055,-0.909675
9,2022-08-18 17:00:00+00:00,161.914,162.277,161.910,162.136,162.29006,163.213900,-0.923840
10,2022-08-18 21:00:00+00:00,162.119,162.424,161.956,162.256,162.28340,163.203430,-0.920030
11,2022-08-19 01:00:00+00:00,162.258,162.468,162.082,162.194,162.26442,163.193345,-0.928925
12,2022-08-19 05:00:00+00:00,162.194,162.844,162.103,162.349,162.25310,163.181230,-0.928130
13,2022-08-19 09:00:00+00:00,162.349,162.378,161.862,162.108,162.23458,163.166560,-0.931980
14,2022-08-19 13:00:00+00:00,162.110,162.198,161.640,161.861,162.20212,163.157795,-0.955675
15,2022-08-19 17:00:00+00:00,161.861,162.091,161.656,161.954,162.17394,163.154560,-0.980620
16,2022-08-21 21:00:00+00:00,161.967,162.147,161.742,162.084,162.15234,163.155680,-1.003340
17,2022-08-22 01:00:00+00:00,162.091,162.537,162.077,162.366,162.13600,163.155120,-1.019120
18,2022-08-22 05:00:00+00:00,162.364,162.406,161.161,161.758,162.10728,163.152340,-1.045060
19,2022-08-22 09:00:00+00:00,161.756,162.187,161.434,162.129,162.08744,163.155325,-1.067885
20,2022-08-22 13:00:00+00:00,162.132,162.160,161.593,161.856,162.05940,163.156025,-1.096625
21,2022-08-22 17:00:00+00:00,161.856,161.862,161.557,161.798,162.04132,163.161025,-1.119705
22,2022-08-22 21:00:00+00:00,161.751,162.064,161.588,161.602,162.02644,163.160675,-1.134235
23,2022-08-23 01:00:00+00:00,161.598,161.797,161.378,161.502,162.00956,163.157935,-1.148375
24,2022-08-23 05:00:00+00:00,161.498,161.660,160.808,161.606,161.99964,163.156395,-1.156755
25,2022-08-23 09:00:00+00:00,161.604,161.807,161.428,161.790,161.98952,163.154755,-1.165235
26,2022-08-23 13:00:00+00:00,161.788,162.313,161.207,161.660,161.97820,163.148405,-1.170205
27,2022-08-23 17:00:00+00:00,161.659,161.914,161.611,161.798,161.98556,163.144340,-1.158780
28,2022-08-23 21:00:00+00:00,161.923,161.943,161.696,161.723,161.97370,163.136180,-1.162480
29,2022-08-24 01:00:00+00:00,161.724,161.827,161.168,161.394,161.95634,163.125505,-1.169165
30,2022-08-24 05:00:00+00:00,161.394,161.814,161.240,161.334,161.93514,163.113015,-1.177875
31,2022-08-24 09:00:00+00:00,161.335,161.378,160.839,161.122,161.90910,163.104780,-1.195680
32,2022-08-24 13:00:00+00:00,161.120,161.777,161.090,161.547,161.89476,163.102525,-1.207765
33,2022-08-24 17:00:00+00:00,161.547,161.810,161.500,161.748,161.89146,163.093620,-1.202160
34,2022-08-24 21:00:00+00:00,161.700,161.909,161.540,161.743,161.88560,163.083995,-1.198395
35,2022-08-25 01:00:00+00:00,161.745,161.788,161.482,161.723,161.87948,163.073765,-1.194285
36,2022-08-25 05:00:00+00:00,161.723,161.998,161.486,161.632,161.88132,163.062555,-1.181235
37,2022-08-25 09:00:00+00:00,161.630,161.751,161.324,161.550,161.88476,163.049165,-1.164405
38,2022-08-25 13:00:00+00:00,161.548,161.920,161.342,161.515,161.89424,163.037195,-1.142955
39,2022-08-25 17:00:00+00:00,161.515,161.611,161.328,161.532,161.91664,163.024605,-1.107965
40,2022-08-25 21:00:00+00:00,161.545,161.598,161.352,161.476,161.92832,163.015605,-1.087285
41,2022-08-26 01:00:00+00:00,161.478,161.720,161.448,161.578,161.94608,163.006445,-1.060365
42,2022-08-26 05:00:00+00:00,161.580,161.694,161.282,161.566,161.97006,162.998225,-1.028165
43,2022-08-26 09:00:00+00:00,161.565,162.141,161.565,162.006,161.99362,162.993785,-1.000165
44,2022-08-26 13:00:00+00:00,162.004,162.694,161.222,161.406,161.99722,162.989225,-0.992005
45,2022-08-26 17:00:00+00:00,161.406,161.569,161.228,161.546,161.98294,162.986570,-1.003630
46,2022-08-28 21:00:00+00:00,161.516,161.786,161.418,161.615,161.96768,162.980650,-1.012970
47,2022-08-29 01:00:00+00:00,161.612,161.876,161.472,161.840,161.95624,162.976280,-1.020040
48,2022-08-29 05:00:00+00:00,161.842,162.194,161.700,161.707,161.94230,162.971445,-1.029145
49,2022-08-29 09:00:00+00:00,161.706,162.454,161.598,162.284,161.93634,162.967325,-1.030985

In [67]:
# We need to look for delta sign changes to identify buy/sell signals
df_an['DELTA_PREV'] = df_an['DELTA'].shift(1)

In [68]:
def is_trade(row):
    if row['DELTA'] > 0 and row['DELTA_PREV'] < 0:
        return BUY
    elif row['DELTA'] < 0 and row['DELTA_PREV'] > 0:
        return SELL
    return NONE

In [69]:
df_an['TRADE'] = df_an.apply(is_trade, axis=1)

In [70]:
# df_an.head(50)
df_an.head()

,time,mid_o,mid_h,mid_l,mid_c,MA_50,MA_200,DELTA,DELTA_PREV,TRADE
0,2022-08-17 05:00:00+00:00,162.583,163.392,162.482,163.174,162.32144,163.256840,-0.935400,NaN,0
1,2022-08-17 09:00:00+00:00,163.174,163.368,162.896,162.974,162.34340,163.253090,-0.909690,-0.935400,0
2,2022-08-17 13:00:00+00:00,162.976,163.570,162.792,163.032,162.37156,163.248335,-0.876775,-0.909690,0
3,2022-08-17 17:00:00+00:00,163.030,163.224,162.622,162.752,162.38692,163.249945,-0.863025,-0.876775,0
4,2022-08-17 21:00:00+00:00,162.701,162.877,162.430,162.468,162.37192,163.247515,-0.875595,-0.863025,0

In [71]:

df_trades = df_an[df_an['TRADE'] != NONE].copy()
print(df_trades.shape)
df_trades.head()

(22, 10)

,time,mid_o,mid_h,mid_l,mid_c,MA_50,MA_200,DELTA,DELTA_PREV,TRADE
94,2022-09-07 21:00:00+00:00,165.785,166.325,165.761,166.083,162.52420,162.482745,0.041455,-0.039300,1
166,2022-09-25 21:00:00+00:00,155.138,155.640,149.333,149.497,162.73530,162.746095,-0.010795,0.256970,-1
235,2022-10-11 09:00:00+00:00,160.909,161.766,160.778,161.505,162.13024,162.123840,0.006400,-0.101630,1
388,2022-11-15 22:00:00+00:00,165.286,165.706,164.708,165.493,166.24186,166.275035,-0.033175,0.000815,-1
513,2022-12-14 18:00:00+00:00,167.771,168.395,167.361,168.376,167.11960,167.093855,0.025745,-0.052325,1

In [72]:
cp = CandlePlot(df_an.iloc[:65])
cp.show_plot(line_traces=[MA_S,MA_L])

In [73]:
# df.groupby(stuff...).sum(numeric_only=True) will sum only the numeric columns

In [74]:
ic.LoadInstruments("../data")

In [75]:
ic.instruments_dict[pair]

{'name': 'GBP_JPY', 'ins_type': 'CURRENCY', 'displayName': 'GBP/JPY', 'pipLocation': 0.01, 'tradeUnitsPrecision': 0, 'marginRate': 0.05}

In [76]:
ins_data = ic.instruments_dict[pair]

In [77]:
df_trades.shape
# Note that every trade will have a pip difference, this will cause some loss in the backtest

(22, 10)

In [78]:
df_trades['DIFF'] = df_trades['mid_c'].diff().shift(-1)
df_trades.fillna(0, inplace=True)

In [79]:
df_trades['GAIN'] = df_trades['DIFF'] / ins_data.pipLocation
df_trades['GAIN'] = df_trades['GAIN'] * df_trades['TRADE']

In [80]:
df_trades.GAIN.sum()

np.float64(-2469.0999999999917)

In [81]:
df_trades['GAIN_C'] = df_trades['GAIN'].cumsum()
df_trades.head()

,time,mid_o,mid_h,mid_l,mid_c,MA_50,MA_200,DELTA,DELTA_PREV,TRADE,DIFF,GAIN,GAIN_C
94,2022-09-07 21:00:00+00:00,165.785,166.325,165.761,166.083,162.52420,162.482745,0.041455,-0.039300,1,-16.586,-1658.6,-1658.6
166,2022-09-25 21:00:00+00:00,155.138,155.640,149.333,149.497,162.73530,162.746095,-0.010795,0.256970,-1,12.008,-1200.8,-2859.4
235,2022-10-11 09:00:00+00:00,160.909,161.766,160.778,161.505,162.13024,162.123840,0.006400,-0.101630,1,3.988,398.8,-2460.6
388,2022-11-15 22:00:00+00:00,165.286,165.706,164.708,165.493,166.24186,166.275035,-0.033175,0.000815,-1,2.883,-288.3,-2748.9
513,2022-12-14 18:00:00+00:00,167.771,168.395,167.361,168.376,167.11960,167.093855,0.025745,-0.052325,1,-7.539,-753.9,-3502.8

In [82]:

cp = CandlePlot(df_trades,candles= False)
cp.show_plot(line_traces=['GAIN_C'])